// This file is part of the FidelityFX SDK.
//
// Copyright (C) 2024 Advanced Micro Devices, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and /or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
//
// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: MIT

#ifndef FFX_FRAMEINTERPOLATION_RESOURCES_H
#define FFX_FRAMEINTERPOLATION_RESOURCES_H

#if defined(FFX_CPU) || defined(FFX_GPU)
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_NULL 0

// Inputs
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_DEPTH               1
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_MOTION_VECTORS      2
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_OPTICAL_FLOW_VECTOR 3
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_DYNAMIC_MASK_TP1    4
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_DYNAMIC_MASK_TM1    5
// ARM_TODO: Potentially we don't need this!
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_OPTICAL_FLOW_SCENE_CHANGE_DETECTION 6
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_PREVIOUS_INTERPOLATION_SOURCE       7
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_CURRENT_INTERPOLATION_SOURCE        8
// Output
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_PRESENT_BACKBUFFER 9
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_OUTPUT             10
// Intermediates
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_MV_HOLES_TP1           11
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_MV_HOLES_TM1           12
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_WARP_MOTION_QDATA_TP1  13
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_WARP_FLOW_QDATA_TM1    14
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_WARP_FILLED_MOTION_TP1 15
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_WARP_FILLED_FLOW_TM1   16
// ARM_TODO
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_IN_TENSOR         17
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_OUT_PARAMS_TENSOR 18

#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_DEPTH_TM1      19
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_DEPTH_TM1_NEXT 20

// Internal colour buffers for OF input downsample (pipeline v1.0.0)
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_COLOUR_P1_INTERNAL 21
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_COLOUR_M1_INTERNAL 22
// Ping-pong backup of PREVIOUS_INTERPOLATION_SOURCE used when the interpolation
// pass runs asynchronously: the in-flight frame keeps reading the previous
// source while the next frame writes into this backup.
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_PREVIOUS_INTERPOLATION_SOURCE_BACKUP 23
//
#define FFX_FRAMEINTERPOLATION_RESOURCE_IDENTIFIER_COUNT 24
//
#define FFX_FRAMEINTERPOLATION_CONSTANTBUFFER_IDENTIFIER 0
//
#define FFX_FRAMEINTERPOLATION_CONSTANTBUFFER_COUNT 1

#define FFX_FRAMEINTERPOLATION_THREAD_GROUP_WIDTH  16
#define FFX_FRAMEINTERPOLATION_THREAD_GROUP_HEIGHT 16
#define FFX_FRAMEINTERPOLATION_THREAD_GROUP_DEPTH  1

// Resolution lane caps (maximum height in pixels) for the nfru pipeline v1 lane model.
#define FFX_FRAMEINTERPOLATION_OF_INPUT_COLOUR_MAX_HEIGHT 1080
#define FFX_FRAMEINTERPOLATION_MV_DEPTH_LANE_MAX_HEIGHT   540
#define FFX_FRAMEINTERPOLATION_FLOW_LANE_MAX_HEIGHT       270
#define FFX_FRAMEINTERPOLATION_TENSOR_LANE_MAX_HEIGHT     270

#endif  // #if defined(FFX_CPU) || defined(FFX_GPU)

#endif  //!defined( FFX_FRAMEINTERPOLATION_RESOURCES_H )
